name: e_commerce_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dart_code_metrics: ^5.7.6
  go_router: ^14.8.1
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/icon/
    - assets/image/