name: code_generation
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  chopper: ^8.4.0
  chopper_generator: ^8.4.0
  flutter:
    sdk: flutter
  freezed: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.11.1
  build_runner: ^2.10.1

flutter:
  uses-material-design: true
