name: riverpod_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  custom_lint: ^0.8.0
  flutter:
    sdk: flutter

  flutter_riverpod: ^3.0.3
  dio: ^5.9.0
  riverpod_lint: ^3.0.3
  chopper: ^8.4.0
  chopper_generator: ^8.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
